"""Validate completed native builds without reading personal configuration."""
import hashlib
import json
from pathlib import Path
import subprocess


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def tracked_file(path, *, relative_to=None):
    # Mirror ProvenanceInputs.cmake. Hidden source files remain build inputs;
    # only named OS metadata and Python caches are excluded.
    parts = path.relative_to(relative_to).parts if relative_to is not None else path.parts
    return (path.is_file() and "__pycache__" not in parts
            and path.suffix != ".pyc" and path.name != ".DS_Store")


def source_inputs(root):
    paths = {"CMakeLists.txt", "CMakePresets.json", "README.md"}
    for directory in ("src", "setup", "include", "cmake", "scripts", "packaging", "third_party"):
        paths.update(path.relative_to(root).as_posix() for path in (root / directory).rglob("*")
                     if tracked_file(path, relative_to=root))
    return paths


def validate_configuration(root, build):
    """The cache snapshot is generated by CMake, never learned on first build."""
    configured = json.loads((build / "provenance-configure.json").read_text())
    paths = {"CMakeLists.txt"}
    if (root / "CMakePresets.json").is_file():
        paths.add("CMakePresets.json")
    paths.update(path.relative_to(root).as_posix() for path in (root / "cmake").rglob("*")
                 if tracked_file(path, relative_to=root))
    if paths != set(configured.get("source", {})):
        raise SystemExit("Configure input inventory changed; re-run CMake before building")
    for group, base in (("source", root), ("external", Path("/"))):
        for relative, expected in configured.get(group, {}).items():
            path = Path(relative) if group == "external" else base / relative
            if not path.is_file() or sha256(path) != expected:
                raise SystemExit(f"Configure input changed: {path}; re-run CMake before building")
    if sha256(build / "CMakeCache.txt") != sha256(build / "provenance-configured-cache.txt"):
        raise SystemExit("CMakeCache.txt changed since configure; re-run CMake before building")


def validate_provenance(manifest, root, bin_dir, *, binary_dir=None):
    """binary_dir can be a staging directory; build inputs remain at bin_dir."""
    if manifest.get("schema_version") != 2:
        raise SystemExit("Missing completed-build provenance; perform a full build")
    inputs = manifest.get("inputs", {})
    if set(inputs.get("source", {})) != source_inputs(root):
        raise SystemExit("Build source inventory changed; perform a full build")
    if set(inputs.get("build", {})) != {"CMakeCache.txt", "dependency-manifest.json", "provenance-dependencies.cmake",
                                       "provenance-configure.json", "provenance-configured-cache.txt"}:
        raise SystemExit("Missing build input provenance")
    if not isinstance(inputs.get("external_files"), list) or not isinstance(inputs.get("external_roots"), list):
        raise SystemExit("Missing dependency inventory provenance; perform a full build")
    external = {Path(path).as_posix() for path in inputs["external_files"] if tracked_file(Path(path))}
    for directory in inputs["external_roots"]:
        root_path = Path(directory)
        if not root_path.is_dir():
            raise SystemExit(f"Dependency directory missing: {directory}; perform a full build")
        external.update(path.as_posix() for path in root_path.rglob("*") if tracked_file(path))
    if external != set(inputs.get("external", {})):
        raise SystemExit("Dependency inventory changed; perform a full build")
    for group, base in (("source", root), ("build", bin_dir.parent), ("external", Path("/"))):
        for relative, expected in inputs.get(group, {}).items():
            path = Path(relative) if group == "external" else base / relative
            if not path.is_file() or sha256(path) != expected:
                raise SystemExit(f"Build input changed: {path}; perform a full build")
    validate_configuration(root, bin_dir.parent)
    suffix = ".exe" if manifest["target"] == "windows-x64" else ""
    if set(manifest.get("binaries", {})) != {"main", "setup"}:
        raise SystemExit("Missing binary provenance")
    for name, expected in manifest["binaries"].items():
        path = (binary_dir or bin_dir) / (name + suffix)
        if not path.is_file() or path.is_symlink() or sha256(path) != expected:
            raise SystemExit(f"Binary differs from completed build: {path}")


def validate_release(manifest, root):
    revision = manifest.get("revision", "")
    import re
    if not re.fullmatch(r"([0-9a-f]{40}|[0-9a-f]{64})", revision) or manifest.get("dirty") is not False:
        raise SystemExit("Ambiguous release provenance: invalid revision or modified working tree")
    try:
        head = subprocess.run(["git", "rev-parse", "HEAD"], cwd=root, capture_output=True,
                              text=True, check=True).stdout.strip()
        status = subprocess.run(["git", "status", "--porcelain", "--untracked-files=normal"],
                                cwd=root, capture_output=True, text=True, check=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError) as error:
        raise SystemExit(f"Cannot verify release Git provenance: {error}") from error
    if head != revision or status:
        raise SystemExit("Release checkout differs from completed build")
