foreach(_required BINARY_FILE RECEIPT_FILE INPUT_FILE ADMISSION_FILE)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "Missing receipt argument: ${_required}")
    endif()
endforeach()
foreach(_file "${INPUT_FILE}" "${ADMISSION_FILE}")
    if(NOT EXISTS "${_file}" OR IS_DIRECTORY "${_file}" OR IS_SYMLINK "${_file}")
        message(FATAL_ERROR "Missing or invalid provenance file: ${_file}")
    endif()
endforeach()
if(IS_DIRECTORY "${RECEIPT_FILE}" OR IS_SYMLINK "${RECEIPT_FILE}")
    message(FATAL_ERROR "Invalid receipt path")
endif()
file(READ "${ADMISSION_FILE}" _admission)
foreach(_field mode inputs binary receipt binary_path receipt_path)
    string(JSON _admitted_${_field} ERROR_VARIABLE _error GET "${_admission}" "${_field}")
    if(_error)
        message(FATAL_ERROR "Invalid build admission: ${_field}")
    endif()
endforeach()
# file(WRITE) uses native text newlines on Windows. Hash the same normalized
# text as the generated header and finalizer, not the CRLF bytes on disk.
file(READ "${INPUT_FILE}" _inputs)
string(SHA256 _fingerprint "${_inputs}")
string(SHA256 _binary_path "${BINARY_FILE}")
string(SHA256 _receipt_path "${RECEIPT_FILE}")
if(NOT _admitted_inputs STREQUAL _fingerprint
        OR NOT _admitted_binary_path STREQUAL _binary_path
        OR NOT _admitted_receipt_path STREQUAL _receipt_path)
    message(FATAL_ERROR "Build admission does not match receipt inputs or paths")
endif()
if(PREPARE_LINK)
    if(NOT _admitted_mode STREQUAL "preserve" AND NOT _admitted_mode STREQUAL "rebuild")
        message(FATAL_ERROR "Invalid executable link admission")
    endif()
    if(IS_DIRECTORY "${BINARY_FILE}" OR IS_SYMLINK "${BINARY_FILE}")
        message(FATAL_ERROR "Invalid executable path")
    endif()
    file(REMOVE "${BINARY_FILE}" "${RECEIPT_FILE}")
    if(EXISTS "${BINARY_FILE}" OR EXISTS "${RECEIPT_FILE}")
        message(FATAL_ERROR "Cannot invalidate executable before linking")
    endif()
    file(WRITE "${ADMISSION_FILE}" "{\"mode\":\"rebuild\",\"inputs\":\"${_fingerprint}\",\"binary\":\"\",\"receipt\":\"\",\"binary_path\":\"${_binary_path}\",\"receipt_path\":\"${_receipt_path}\"}")
    return()
endif()
if(NOT EXISTS "${BINARY_FILE}" OR IS_DIRECTORY "${BINARY_FILE}" OR IS_SYMLINK "${BINARY_FILE}")
    message(FATAL_ERROR "Missing or invalid linked executable: ${BINARY_FILE}")
endif()
file(SHA256 "${BINARY_FILE}" _hash)
if(_admitted_mode STREQUAL "preserve")
    if(NOT EXISTS "${RECEIPT_FILE}")
        message(FATAL_ERROR "Previously admitted receipt disappeared")
    endif()
    file(SHA256 "${RECEIPT_FILE}" _receipt_hash)
    if(NOT _admitted_binary STREQUAL _hash OR NOT _admitted_receipt STREQUAL _receipt_hash)
        message(FATAL_ERROR "Executable or receipt changed after build admission; rebuild required")
    endif()
    return()
elseif(NOT _admitted_mode STREQUAL "rebuild" OR EXISTS "${RECEIPT_FILE}"
        OR NOT _admitted_binary STREQUAL "" OR NOT _admitted_receipt STREQUAL "")
    message(FATAL_ERROR "Invalid executable rebuild admission")
endif()
file(WRITE "${RECEIPT_FILE}" "{\"binary\":\"${_hash}\",\"inputs\":\"${_fingerprint}\"}")
file(SHA256 "${RECEIPT_FILE}" _receipt_hash)
# Consume permission to attest. A repeated POST_BUILD must preserve these exact
# bytes, even when the generator schedules that event without another link.
file(WRITE "${ADMISSION_FILE}" "{\"mode\":\"preserve\",\"inputs\":\"${_fingerprint}\",\"binary\":\"${_hash}\",\"receipt\":\"${_receipt_hash}\",\"binary_path\":\"${_binary_path}\",\"receipt_path\":\"${_receipt_path}\"}")
