# Dependency resolution is deliberately explicit: SDK on macOS; verified local prefix elsewhere.
if(APPLE)
    execute_process(COMMAND xcrun --sdk macosx --show-sdk-path OUTPUT_VARIABLE ITU_APPLE_SDK
        OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    file(REAL_PATH "${ITU_APPLE_SDK}" ITU_APPLE_SDK)
    find_path(ITU_CURL_INCLUDE_DIR curl/curl.h PATHS "${ITU_APPLE_SDK}/usr/include" NO_DEFAULT_PATH REQUIRED)
    find_library(ITU_CURL_LIBRARY NAMES curl libcurl.tbd PATHS "${ITU_APPLE_SDK}/usr/lib" NO_DEFAULT_PATH REQUIRED)
    file(REAL_PATH "${ITU_CURL_INCLUDE_DIR}" _curl_include)
    file(REAL_PATH "${ITU_CURL_LIBRARY}" _curl_library)
    cmake_path(IS_PREFIX ITU_APPLE_SDK "${_curl_include}" NORMALIZE _sdk_include)
    cmake_path(IS_PREFIX ITU_APPLE_SDK "${_curl_library}" NORMALIZE _sdk_library)
    if(NOT _sdk_include OR NOT _sdk_library)
        message(FATAL_ERROR "Cached curl must resolve inside active Apple SDK; use a clean build directory")
    endif()
    add_library(CURL::libcurl UNKNOWN IMPORTED)
    set_target_properties(CURL::libcurl PROPERTIES IMPORTED_LOCATION "${ITU_CURL_LIBRARY}"
        INTERFACE_INCLUDE_DIRECTORIES "${ITU_CURL_INCLUDE_DIR}")
    file(STRINGS "${ITU_CURL_INCLUDE_DIR}/curl/curlver.h" _version_line REGEX "^#define LIBCURL_VERSION \"")
    string(REGEX MATCH "[0-9]+\\.[0-9]+\\.[0-9]+" ITU_CURL_VERSION "${_version_line}")
    if(ITU_CURL_VERSION VERSION_LESS "7.85.0")
        message(FATAL_ERROR "libcurl 7.85.0+ is required")
    endif()
    set(ITU_DEPENDENCY_MANIFEST "{\"curl\": {\"version\": \"${ITU_CURL_VERSION}\", \"source\": \"Apple SDK/system\"}}")
else()
    set(ITU_DEPS_PREFIX "${CMAKE_SOURCE_DIR}/.deps/${ITU_TARGET}/install" CACHE PATH "Project-local verified dependencies")
    if(NOT EXISTS "${ITU_DEPS_PREFIX}/itu-dependencies.cmake")
        message(FATAL_ERROR "Run python scripts/bootstrap.py --target ${ITU_TARGET}; only project-local .deps prefixes are accepted")
    endif()
    file(REAL_PATH "${CMAKE_SOURCE_DIR}/.deps" _deps_root)
    file(REAL_PATH "${ITU_DEPS_PREFIX}" _deps_prefix)
    cmake_path(IS_PREFIX _deps_root "${_deps_prefix}" NORMALIZE _project_local)
    if(NOT _project_local)
        message(FATAL_ERROR "Run python scripts/bootstrap.py --target ${ITU_TARGET}; only project-local .deps prefixes are accepted")
    endif()
    file(SHA256 "${CMAKE_SOURCE_DIR}/cmake/dependencies.lock.json" ITU_EXPECTED_LOCK_SHA256)
    include("${ITU_DEPS_PREFIX}/itu-dependencies.cmake")
    if(NOT ITU_INSTALLED_LOCK_SHA256 STREQUAL ITU_EXPECTED_LOCK_SHA256 OR NOT ITU_INSTALLED_TARGET STREQUAL ITU_TARGET)
        message(FATAL_ERROR "Dependencies do not match target/lock; rerun project-local bootstrap")
    endif()
    foreach(_component curl zlib nghttp2)
        if(NOT EXISTS "${ITU_DEPS_PREFIX}/${ITU_${_component}_LIBRARY}")
            message(FATAL_ERROR "Missing local static dependency: ${_component}")
        endif()
        add_library(itu_${_component} STATIC IMPORTED)
        set_target_properties(itu_${_component} PROPERTIES IMPORTED_LOCATION "${ITU_DEPS_PREFIX}/${ITU_${_component}_LIBRARY}"
            INTERFACE_INCLUDE_DIRECTORIES "${ITU_DEPS_PREFIX}/include")
    endforeach()
    add_library(CURL::libcurl ALIAS itu_curl)
    set_property(TARGET itu_curl PROPERTY INTERFACE_COMPILE_DEFINITIONS CURL_STATICLIB)
    target_link_libraries(itu_curl INTERFACE itu_nghttp2 itu_zlib)
    if(WIN32)
        target_link_libraries(itu_curl INTERFACE ws2_32 crypt32 secur32 bcrypt advapi32 normaliz iphlpapi)
    else()
        foreach(_component ssl crypto)
            if(NOT EXISTS "${ITU_DEPS_PREFIX}/lib/lib${_component}.a")
                message(FATAL_ERROR "Missing project-local OpenSSL ${_component}")
            endif()
            add_library(itu_${_component} STATIC IMPORTED)
            set_target_properties(itu_${_component} PROPERTIES IMPORTED_LOCATION "${ITU_DEPS_PREFIX}/lib/lib${_component}.a")
        endforeach()
        find_package(Threads REQUIRED)
        target_link_libraries(itu_curl INTERFACE itu_ssl itu_crypto Threads::Threads ${CMAKE_DL_LIBS})
    endif()
    file(READ "${ITU_DEPS_PREFIX}/dependency-manifest.json" ITU_DEPENDENCY_MANIFEST)
endif()
