# Keep the source inventory in sync with scripts/provenance.py. Never include
# personal runtime configuration. Hash contents, not Git's boolean dirty flag.
if(START_BUILD)
    file(REMOVE "${BINARY_DIR}/bin/build-manifest.json")
    foreach(_target main setup)
        file(REMOVE "${BINARY_DIR}/${_target}-${BUILD_CONFIG}.admission.json")
    endforeach()
endif()
if(NOT EXISTS "${BINARY_DIR}/provenance-configure.json"
        OR NOT EXISTS "${BINARY_DIR}/provenance-configured-cache.txt")
    message(FATAL_ERROR "Missing configure provenance; re-run CMake before building")
endif()
file(READ "${BINARY_DIR}/provenance-configure.json" _conf_json)
set(_curr_conf_files "CMakeLists.txt")
if(EXISTS "${SOURCE_DIR}/CMakePresets.json")
    list(APPEND _curr_conf_files "CMakePresets.json")
endif()
file(GLOB_RECURSE _curr_cmake_inputs LIST_DIRECTORIES false RELATIVE "${SOURCE_DIR}" "${SOURCE_DIR}/cmake/*")
foreach(_file IN LISTS _curr_cmake_inputs)
    if(NOT _file MATCHES "(^|/)__pycache__/" AND NOT _file MATCHES "\\.pyc$"
            AND NOT _file MATCHES "(^|/)\\.DS_Store$")
        list(APPEND _curr_conf_files "${_file}")
    endif()
endforeach()
list(REMOVE_DUPLICATES _curr_conf_files)
list(SORT _curr_conf_files)
string(JSON _conf_count LENGTH "${_conf_json}" source)
list(LENGTH _curr_conf_files _curr_count)
if(NOT _conf_count EQUAL _curr_count)
    message(FATAL_ERROR "Configure files inventory changed since last CMake configure; re-run CMake before building")
endif()
foreach(_curr_file IN LISTS _curr_conf_files)
    file(SHA256 "${SOURCE_DIR}/${_curr_file}" _curr_file_hash)
    string(JSON _expected_file_hash ERROR_VARIABLE _lookup_err GET "${_conf_json}" source "${_curr_file}")
    if(_lookup_err OR NOT _curr_file_hash STREQUAL _expected_file_hash)
        message(FATAL_ERROR "${_curr_file} changed since last CMake configure; re-run CMake before building")
    endif()
endforeach()
string(JSON _external_count LENGTH "${_conf_json}" external)
if(_external_count GREATER 0)
    math(EXPR _external_last "${_external_count} - 1")
    foreach(_index RANGE 0 ${_external_last})
        string(JSON _file MEMBER "${_conf_json}" external ${_index})
        if(NOT EXISTS "${_file}")
            message(FATAL_ERROR "Configure input missing: ${_file}; re-run CMake before building")
        endif()
        file(SHA256 "${_file}" _hash)
        string(JSON _expected_hash GET "${_conf_json}" external "${_file}")
        if(NOT _hash STREQUAL _expected_hash)
            message(FATAL_ERROR "${_file} changed since last CMake configure; re-run CMake before building")
        endif()
    endforeach()
endif()
file(SHA256 "${BINARY_DIR}/CMakeCache.txt" _curr_cache)
file(SHA256 "${BINARY_DIR}/provenance-configured-cache.txt" _conf_cache)
if(NOT _curr_cache STREQUAL _conf_cache)
    message(FATAL_ERROR "CMakeCache.txt changed since last CMake configure; re-run CMake before building")
endif()
set(_inputs CMakeLists.txt CMakePresets.json README.md)
foreach(_directory src setup include cmake scripts packaging third_party)
    file(GLOB_RECURSE _files LIST_DIRECTORIES false RELATIVE "${SOURCE_DIR}"
        "${SOURCE_DIR}/${_directory}/*")
    foreach(_file IN LISTS _files)
        if(NOT _file MATCHES "(^|/)__pycache__/" AND NOT _file MATCHES "\\.pyc$"
                AND NOT _file MATCHES "(^|/)\\.DS_Store$")
            list(APPEND _inputs "${_file}")
        endif()
    endforeach()
endforeach()
list(SORT _inputs)
set(PROVENANCE_INPUTS "{\"source\":{},\"build\":{},\"external\":{}}")
foreach(_file IN LISTS _inputs)
    file(SHA256 "${SOURCE_DIR}/${_file}" _hash)
    string(JSON PROVENANCE_INPUTS SET "${PROVENANCE_INPUTS}" source "${_file}" "\"${_hash}\"")
endforeach()
foreach(_file CMakeCache.txt dependency-manifest.json provenance-dependencies.cmake
        provenance-configure.json provenance-configured-cache.txt)
    file(SHA256 "${BINARY_DIR}/${_file}" _hash)
    string(JSON PROVENANCE_INPUTS SET "${PROVENANCE_INPUTS}" build "${_file}" "\"${_hash}\"")
endforeach()
include("${BINARY_DIR}/provenance-dependencies.cmake")
set(_external_files ${PROVENANCE_EXTERNAL_FILES})
foreach(_kind FILES ROOTS)
    string(TOLOWER "${_kind}" _key)
    string(JSON PROVENANCE_INPUTS SET "${PROVENANCE_INPUTS}" "external_${_key}" "[]")
    set(_index 0)
    foreach(_path IN LISTS PROVENANCE_EXTERNAL_${_kind})
        # JSON-escape paths (including Windows backslashes).
        string(REPLACE "\\" "\\\\" _escaped "${_path}")
        string(REPLACE "\"" "\\\"" _escaped "${_escaped}")
        string(JSON PROVENANCE_INPUTS SET "${PROVENANCE_INPUTS}" "external_${_key}" ${_index} "\"${_escaped}\"")
        math(EXPR _index "${_index} + 1")
    endforeach()
endforeach()
foreach(_root IN LISTS PROVENANCE_EXTERNAL_ROOTS)
    if(NOT IS_DIRECTORY "${_root}")
        message(FATAL_ERROR "Missing dependency input directory: ${_root}")
    endif()
    file(GLOB_RECURSE _files LIST_DIRECTORIES false "${_root}/*")
    list(APPEND _external_files ${_files})
endforeach()
list(REMOVE_DUPLICATES _external_files)
list(SORT _external_files)
foreach(_file IN LISTS _external_files)
    if(_file MATCHES "(^|/)__pycache__/" OR _file MATCHES "\\.pyc$" OR _file MATCHES "(^|/)\\.DS_Store$")
        continue()
    endif()
    file(SHA256 "${_file}" _hash)
    string(JSON PROVENANCE_INPUTS SET "${PROVENANCE_INPUTS}" external "${_file}" "\"${_hash}\"")
endforeach()
if(START_BUILD)
    file(WRITE "${BINARY_DIR}/provenance-start.json" "${PROVENANCE_INPUTS}")
    string(SHA256 _fingerprint "${PROVENANCE_INPUTS}")
    foreach(_target main setup)
        string(TOUPPER "${_target}" _upper_target)
        set(_binary "${${_upper_target}_FILE}")
        set(_receipt "${BINARY_DIR}/${_target}-${BUILD_CONFIG}.sha256")
        set(_admission "${BINARY_DIR}/${_target}-${BUILD_CONFIG}.admission.json")
        if(NOT IS_ABSOLUTE "${_binary}" OR IS_DIRECTORY "${_binary}" OR IS_SYMLINK "${_binary}"
                OR IS_DIRECTORY "${_receipt}" OR IS_SYMLINK "${_receipt}")
            message(FATAL_ERROR "Invalid ${_target} provenance output path")
        endif()
        set(_mode rebuild)
        set(_binary_hash "")
        set(_receipt_hash "")
        if(EXISTS "${_binary}" AND EXISTS "${_receipt}")
            file(SHA256 "${_binary}" _binary_hash)
            file(READ "${_receipt}" _receipt_json)
            string(JSON _expected_binary ERROR_VARIABLE _binary_error GET "${_receipt_json}" binary)
            string(JSON _expected_inputs ERROR_VARIABLE _inputs_error GET "${_receipt_json}" inputs)
            if(NOT _binary_error AND NOT _inputs_error
                    AND _expected_binary STREQUAL _binary_hash
                    AND _expected_inputs STREQUAL _fingerprint)
                set(_mode preserve)
                file(SHA256 "${_receipt}" _receipt_hash)
            endif()
        endif()
        if(_mode STREQUAL "rebuild")
            # Never let a POST_BUILD event alone bless stale executable bytes.
            # A missing output makes every supported generator link it again.
            file(REMOVE "${_binary}" "${_receipt}")
            if(EXISTS "${_binary}" OR EXISTS "${_receipt}")
                message(FATAL_ERROR "Cannot invalidate ${_target} provenance outputs")
            endif()
            set(_binary_hash "")
        endif()
        string(SHA256 _binary_path "${_binary}")
        string(SHA256 _receipt_path "${_receipt}")
        file(WRITE "${_admission}" "{\"mode\":\"${_mode}\",\"inputs\":\"${_fingerprint}\",\"binary\":\"${_binary_hash}\",\"receipt\":\"${_receipt_hash}\",\"binary_path\":\"${_binary_path}\",\"receipt_path\":\"${_receipt_path}\"}")
    endforeach()
    set(_header "/* Generated build input fingerprint. */\n#define ITU_BUILD_INPUT_FINGERPRINT \"${_fingerprint}\"\n")
    set(_previous_header "")
    if(EXISTS "${BINARY_DIR}/provenance-inputs.h")
        file(READ "${BINARY_DIR}/provenance-inputs.h" _previous_header)
    endif()
    if(NOT _previous_header STREQUAL _header)
        # Apple's supported /usr/bin/make 3.81 compares whole-second mtimes.
        # A second input change immediately after a successful build otherwise
        # can leave some objects appearing as new as the changed header. Cross
        # that timestamp boundary before updating; unchanged inputs never wait.
        execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1 COMMAND_ERROR_IS_FATAL ANY)
        file(WRITE "${BINARY_DIR}/provenance-inputs.h" "${_header}")
    endif()
endif()
