# Keep the source inventory in sync with scripts/provenance.py. Never include
# personal runtime configuration. Hash contents, not Git's boolean dirty flag.
if(START_BUILD)
    file(REMOVE "${BINARY_DIR}/bin/build-manifest.json")
endif()
set(_inputs CMakeLists.txt CMakePresets.json README.md)
foreach(_directory src setup include cmake scripts packaging third_party)
    file(GLOB_RECURSE _files LIST_DIRECTORIES false RELATIVE "${SOURCE_DIR}"
        "${SOURCE_DIR}/${_directory}/*")
    foreach(_file IN LISTS _files)
        if(NOT _file MATCHES "(^|/)__pycache__/" AND NOT _file MATCHES "\\.pyc$")
            list(APPEND _inputs "${_file}")
        endif()
    endforeach()
endforeach()
list(SORT _inputs)
set(PROVENANCE_INPUTS "{\"source\":{},\"build\":{},\"external\":{}}")
foreach(_file IN LISTS _inputs)
    file(SHA256 "${SOURCE_DIR}/${_file}" _hash)
    string(JSON PROVENANCE_INPUTS SET "${PROVENANCE_INPUTS}" source "${_file}" "\"${_hash}\"")
endforeach()
foreach(_file CMakeCache.txt dependency-manifest.json provenance-dependencies.cmake)
    file(SHA256 "${BINARY_DIR}/${_file}" _hash)
    string(JSON PROVENANCE_INPUTS SET "${PROVENANCE_INPUTS}" build "${_file}" "\"${_hash}\"")
endforeach()
include("${BINARY_DIR}/provenance-dependencies.cmake")
foreach(_file IN LISTS PROVENANCE_EXTERNAL_FILES)
    file(SHA256 "${_file}" _hash)
    string(JSON PROVENANCE_INPUTS SET "${PROVENANCE_INPUTS}" external "${_file}" "\"${_hash}\"")
endforeach()
if(START_BUILD)
    file(WRITE "${BINARY_DIR}/provenance-start.json" "${PROVENANCE_INPUTS}")
endif()
